name: HTS - DDN Load Tests
on:
  workflow_dispatch:
    inputs:
      GRAPHQL_ENDPOINT:
        description: 'GraphQL Endpoint'
        required: true
      TEST_DURATION:
        description: 'Test Duration'
        default: '100'
        required: true
      STARTING_ARRIVAL_RATE:
        description: 'Starting Arrival Rate'
        default: '1'
        required: true
      ENDING_ARRIVAL_RATE:
        description: 'Ending Arrival Rate'
        default: '20'
        required: true
      MAXIMUM_VIRTUAL_USER:
        description: 'Maximum Virtual User'
        default: '100'
        required: true
      TEST_NAME:
        description: 'Test Name'
        required: true
      PUSHGATEWAY:
        description: 'Pushgateway'
        required: true
      SERVICE_NAME:
        description: 'Service Name'
        required: true
        type: choice
        options: [ 'team3', 'team2', 'team1', 'SRE']
      QUERY_FILE:
        description: 'Query File'
        required: true
    
jobs:
  hts-load-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Artillery globally
      run: npm install -g artillery2.0.14

    - name: Set environment variables
      run: |
        echo "GRAPHQL_ENDPOINT=${{ github.event.inputs.GRAPHQL_ENDPOINT }}" >> $GITHUB_ENV
        echo "TEST_DURATION=${{ github.event.inputs.TEST_DURATION }}" >> $GITHUB_ENV
        echo "STARTING_ARRIVAL_RATE=${{ github.event.inputs.STARTING_ARRIVAL_RATE }}" >> $GITHUB_ENV
        echo "ENDING_ARRIVAL_RATE=${{ github.event.inputs.ENDING_ARRIVAL_RATE }}" >> $GITHUB_ENV
        echo "MAXIMUM_VIRTUAL_USER=${{ github.event.inputs.MAXIMUM_VIRTUAL_USER }}" >> $GITHUB_ENV
        echo "TEST_NAME=${{ github.event.inputs.TEST_NAME }}" >> $GITHUB_ENV
        echo "PUSHGATEWAY=${{ github.event.inputs.PUSHGATEWAY }}" >> $GITHUB_ENV
        echo "SERVICE_NAME=${{ github.event.inputs.SERVICE_NAME }}" >> $GITHUB_ENV
        echo "QUERY_FILE=${{ github.event.inputs.QUERY_FILE }}" >> $GITHUB_ENV

    - name: Retrieve GraphQL Admin Secret
      id: retrieve-secret
      env:
        HGE: ${{ secrets.HGE }}
      run: |
        python3 .github/scripts/get_secret.py

    # comment if not required
    - name: Set HASURA_CLOUD_PAT
      run: echo "HASURA_CLOUD_PAT=${{ steps.retrieve-secret.outputs.HASURA_CLOUD_PAT }}" >> $GITHUB_ENV

    - name: Generate schema  
      run: |
        cd .github/test-configs/loadTest 
        npm install
        npm run codegen 

    - name: Initiate Load Tests
      run: |
        echo "
          Starting Load Test:
          GRAPHQL ENDPOINT: ${{ github.event.inputs.GRAPHQL_ENDPOINT }} 
          Duration: ${{ github.event.inputs.TEST_DURATION }} 
          TEST NAME: ${{ github.event.inputs.TEST_NAME }} 
          "
        cd .github/test-configs/loadTest
        export DEBUG=http,http:capture,http:response
        artillery run runTest.yml 