FROM python:3.9
WORKDIR /app

COPY ./requirements.txt ./api.py ./.flaskenv ./
COPY . .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt
ENV FLASK_ENV production
# Stage 2: Builder for Node.js dependencies
ENV NODE_VERSION=18.16.1
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version
RUN npm install
RUN npm install artillery
ENV PATH="${PATH}:/app/./node_modules/.bin"

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "--timeout", "14400", "api:app"]
