apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-k8s-check-job
  labels:
    app: postgres-k8s-check
spec:
  template:
    metadata:
      labels:
        app: postgres-k8s-check
    spec:
      serviceAccountName: api # Replace with the service account name which has access to image-pull-secret
      containers:
      - name: postgres-k8s-check
        image: gcr.io/hasura-ee/dart-debug:latest  # Replace with your image name
        env:
        - name: POSTGRES_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: secrets  # Name of the secret
              key: HASURA_GRAPHQL_DATABASE_URL # Key in the secret
        - name: SERVICE_HOST
          value: "api"
        ports:
        - containerPort: 8080  # Expose the port if needed for health checks or other services
      restartPolicy: Never  # Set to Never for Jobs to avoid restarting the container

